version: 2
updates:
  - directory: "/"
    open-pull-requests-limit: 10
    package-ecosystem: github-actions
    rebase-strategy: auto
    pull-request-branch-name:
      separator: "-"
    schedule:
      time: "05:00"
      interval: daily
    commit-message:
      include: "scope"
      prefix: "chore"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    groups:
      python-packages:
        patterns:
          - "*"

