---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "python-example.fullname" . }}
  labels:
    app: {{ template "python-example.name" . }}
    appVersion: {{ .Chart.AppVersion | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "python-example.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "python-example.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.runAsUser }}
      securityContext:
        runAsUser: {{ .Values.runAsUser }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /list
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /list
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
