suite: test deployment that would be fail
templates:
  - templates/configmap.yaml
  - templates/deployment.yaml
tests:
  - it: should fail all kinds of assertion
    values:
      - ./values/image.yaml
    template: templates/deployment.yaml
    set:
      service.internalPort: 8080
    asserts:
      - equal:
          path: spec.template.spec.containers[0].image
          value: nginx:stable
      - notEqual:
          path: spec.template.spec.containers[0].image
          value: apache:latest
      - matchRegex:
          path: metadata.name
          pattern: ^.*-foobar$
      - notMatchRegex:
          path: metadata.name
          pattern: ^.*-basic$
      - contains:
          path: spec.template.spec.containers[0].ports
          content:
            containerPort: 80
      - notContains:
          path: spec.template.spec.containers[0].ports
          content:
            containerPort: 8080
      - notExists:
          path: spec.template
      - exists:
          path: spec.template.nodeSelector
      - isNullOrEmpty:
          path: spec.template.spec.containers[0]
      - isNotNullOrEmpty:
          path: spec.template.spec.containers[0].resources
      - isKind:
          of: Pod
      - isAPIVersion:
          of: v2
      - hasDocuments:
          count: 1
      - matchSnapshot:
          path: spec
      - contains:
          path: spec.template.spec.containers
          content: 'foo'
          count: 1234567890 # or 6.8 or -10 or 0
      - isType:
          path: spec.replicas
          type: string
      - lengthEqual:
          path:  spec.template.spec.containers
          count: 10
      - notLengthEqual:
          path: spec.template.spec.containers
          count: 1
