name: Semantic Release

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v4

    - name: Install semantic release
      id: inst
      shell: bash
      run: |
        python3 -m pip install python-semantic-release
        echo "go to release"
        echo "email=$(git log -n 1 --pretty=format:%ae)" >> $GITHUB_OUTPUT
    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@v9.8.8
      with:
        github_token: ${{ env.GITHUB_TOKEN }}
        root_options: ${{ env.opt_arg }}
        directory: ${{ env.directory }}
        git_committer_email: ${{ steps.inst.outputs.email }}
        git_committer_name: release
      env:
        GH_TOKEN: ${{ env.GITHUB_TOKEN }}
