name: Semantic Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ env.GITHUB_TOKEN }}
    - name: Install semantic release
      id: inst
      shell: bash
      run: |
        python3 -m pip install python-semantic-release
        echo "go to release"
    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@v9.8.8
      with:
        github_token: ${{ env.GITHUB_TOKEN }}
        directory: ${{ env.directory }}
        git_committer_email: ${{ secrets.mail }}
        git_committer_name: release
